/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAiInsightsRouteImport } from './routes/student.ai-insights'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentExaminationsRouteImport } from './routes/student.examinations'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAiInsightsRouteImport } from './routes/teacher.ai-insights'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherExaminationsRouteImport } from './routes/teacher.examinations'
import { Route as TeacherPerformanceRouteImport } from './routes/teacher.performance'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiInsightsRoute = StudentAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExaminationsRoute = StudentExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAiInsightsRoute = TeacherAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExaminationsRoute = TeacherExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPerformanceRoute = TeacherPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/terms': typeof TermsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai-insights': typeof TeacherAiInsightsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai-insights': typeof TeacherAiInsightsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/terms': typeof TermsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/student/ai-insights': typeof StudentAiInsightsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai-insights': typeof TeacherAiInsightsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/performance': typeof TeacherPerformanceRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/student'
    | '/teacher'
    | '/terms'
    | '/courses/$id'
    | '/student/ai-insights'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/courses'
    | '/student/examinations'
    | '/student/grades'
    | '/student/profile'
    | '/teacher/ai-insights'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/courses'
    | '/teacher/examinations'
    | '/teacher/performance'
    | '/teacher/students'
    | '/courses/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/courses/$id'
    | '/student/ai-insights'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/courses'
    | '/student/examinations'
    | '/student/grades'
    | '/student/profile'
    | '/teacher/ai-insights'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/courses'
    | '/teacher/examinations'
    | '/teacher/performance'
    | '/teacher/students'
    | '/courses'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/student'
    | '/teacher'
    | '/terms'
    | '/courses/$id'
    | '/student/ai-insights'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/courses'
    | '/student/examinations'
    | '/student/grades'
    | '/student/profile'
    | '/teacher/ai-insights'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/courses'
    | '/teacher/examinations'
    | '/teacher/performance'
    | '/teacher/students'
    | '/courses/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TermsRoute: typeof TermsRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-insights': {
      id: '/student/ai-insights'
      path: '/ai-insights'
      fullPath: '/student/ai-insights'
      preLoaderRoute: typeof StudentAiInsightsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/examinations': {
      id: '/student/examinations'
      path: '/examinations'
      fullPath: '/student/examinations'
      preLoaderRoute: typeof StudentExaminationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/ai-insights': {
      id: '/teacher/ai-insights'
      path: '/ai-insights'
      fullPath: '/teacher/ai-insights'
      preLoaderRoute: typeof TeacherAiInsightsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/examinations': {
      id: '/teacher/examinations'
      path: '/examinations'
      fullPath: '/teacher/examinations'
      preLoaderRoute: typeof TeacherExaminationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/performance': {
      id: '/teacher/performance'
      path: '/performance'
      fullPath: '/teacher/performance'
      preLoaderRoute: typeof TeacherPerformanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface StudentRouteChildren {
  StudentAiInsightsRoute: typeof StudentAiInsightsRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentExaminationsRoute: typeof StudentExaminationsRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiInsightsRoute: StudentAiInsightsRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentExaminationsRoute: StudentExaminationsRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAiInsightsRoute: typeof TeacherAiInsightsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherExaminationsRoute: typeof TeacherExaminationsRoute
  TeacherPerformanceRoute: typeof TeacherPerformanceRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAiInsightsRoute: TeacherAiInsightsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherExaminationsRoute: TeacherExaminationsRoute,
  TeacherPerformanceRoute: TeacherPerformanceRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TermsRoute: TermsRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
